# -*- coding: utf-8 -*-
"""Nepse_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13gkRhEJma9THPNO6XEbu2ttMLG1hqZrK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#analyze the index change trend for the last 7 days
#analyze the index change trend for the complete data
#print the number of days when the NEPSE index was greater than 2490 among the last 90 days
#calculate the average NEPSE index value for the last 90 days
#identify the maximum and minimum NEPSE index values within the last 90 days

df=pd.read_csv("/content/nepse_last_90_days.csv")

last_7=df.tail(7)
last7_date=last_7['Date']
last7_index=last_7['NEPSE_Index']
last_7

#analyze the index change trend for the last 7 days
plt.plot(last7_date,last7_index,marker="*")
plt.xlabel('Date')
plt.ylabel('NEPSE Index')
plt.title("Analysis of last 7 days NEPSE Data")
plt.show()

#analyze the index change trend for the complete data
date=df['Date']
index=df['NEPSE_Index']
plt.plot(date,index)
plt.xlabel("Date")
plt.ylabel("NEPSE Index")
plt.title("Analysis of NEPSE Data")
plt.show()

#print the number of days when the NEPSE index was greater than 2490 among the last 90 days
new_data=index[df['NEPSE_Index']>2490]
new_data.count()

df.count()

#calculate the average NEPSE index value for the last 90 days
last_90=index.tail(90)
print("The average NEPSE index value for the last 90 days =",last_90.mean())

#identify the maximum and minimum NEPSE index values within the last 90 days
print("Maximum=",last_90.max())
print("Minimum=",last_90.min())